import {
  boolean,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

export const locationTrackerDeviceSchema = pgTable(
  'location_tracker_device',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id').notNull(),
    secretKey: varchar('secret_key'), // One-time password generated by website
    deviceKey: varchar('device_key'), // Device key from Android app
    deviceOs: varchar('device_os'),
    deviceOsVersion: varchar('device_os_version'),
    deviceModel: varchar('device_model'),
    appVersion: varchar('app_version'),
    name: varchar('name', { length: 200 }), // Name given when accepting device
    description: text('description'), // Description given when accepting device
    isAccepted: boolean('is_accepted')
      .default(false)
      .notNull(),
    createdAt: timestamp('created_at')
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .notNull(),
  },
);

export type LocationTrackerDevice =
  typeof locationTrackerDeviceSchema.$inferSelect;
export type NewLocationTrackerDevice =
  typeof locationTrackerDeviceSchema.$inferInsert;
